### ISSUE TITLE
crash loading model

### ISSUE THREAD

**Issue by ehtick** [IFCjs/web-ifc#362]
I use threejs 143 and the latest web-ifc-three and am trying to load a simple ifc model.
The console from the browser shows

web-ifc-api.js:6592 
        
       Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (web-ifc-api.js:6592:19)
    at _abort (web-ifc-api.js:10470:11)
    at web-ifc.wasm:0x113c
    at web-ifc.wasm:0x63127
    at web-ifc.wasm:0x67b05
    at Object.OpenModel (eval at new_ (web-ifc-api.js:9885:31), <anonymous>:9:10)
    at IfcAPI2.OpenModel (web-ifc-api.js:52769:34)
    at IFCParser.newIfcModel (IFCLoader.js:101:41)
    at IFCParser.parse (IFCLoader.js:92:8)
    at async IFCManager.parse (IFCLoader.js:2215:16)
abort @ web-ifc-api.js:6592
_abort @ web-ifc-api.js:10470
$func54 @ web-ifc.wasm:0x113c
$func830 @ web-ifc.wasm:0x63127
$func831 @ web-ifc.wasm:0x67b05
OpenModel @ VM164:9
OpenModel @ web-ifc-api.js:52769
newIfcModel @ IFCLoader.js:101

i use the await for waiting until the model is loaded

        let object = await ifcLoader.loadAsync(this.element.ContentPath);

any idea?

**Comment by beachtom** [comment]
So this should now be fixed - if not can you re-open and pass us the IFC model
