### ISSUE TITLE
[Bug]: CreateIfcGuidToExpressIdMapping Crashes

### ISSUE THREAD

**Issue by fernandovt-lab** [IFCjs/web-ifc#381]
### What happened?

Based on my observations, it appears that some models may have a missing mandatory data field in one of their elements. This can cause the function "CreateIfcGuidToExpressIdMapping" to crash completely, even if the majority of the IFC model is fine. I have noticed this issue occurring in various models from different sources.

### Version

0.0.39

### Relevant log output

```shell
TypeError: Cannot read properties of null (reading 'value')
    at 526551008 (web-ifc-api-node.js:12488:436)
    at IfcAPI2.GetLine (web-ifc-api-node.js:63239:84)
    at IfcAPI2.CreateIfcGuidToExpressIdMapping (web-ifc-api-node.js:63408:27)
```

**Comment by fernandovt-lab** [comment]
I think a possible solution is https://github.com/IFCjs/web-ifc/blob/main/src/web-ifc-api.ts#L806
Replacing those lines of code with

`            for (let y = 0; y < size; y++) {
        try{
          const expressID = lines.get(y);
          const info = this.GetLine(modelID, expressID);
          if (info.GlobalId == null) {
            continue;
          }
          const globalID = info.GlobalId.value;
          map.set(expressID, globalID);
          map.set(globalID, expressID);
        }catch(e){
          continue
        }
      }`

**Comment by fernandovt-lab** [comment]
> Hi, pretty sure this is already fixed and will go out with next release

@beachtom Hi! I just updated to 0.0.40, but the problem seems to not have been resolved on this newer version
