### ISSUE TITLE
[Bug]: Failed Model

### ISSUE THREAD

**Issue by didimitrie** [IFCjs/web-ifc#413]
### What happened?

Heya team! We're seeing this error in Speckle (where we're happily using web-ifc to parse ifc files!). Model that creates it is attached as a zip file.  

[M-TGA-LK-32.zip](https://github.com/IFCjs/web-ifc/files/11653307/M-TGA-LK-32.zip)

```
ERROR: RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info. {"component":"fileimport-service","taskId":"ce6e17f8b0","fileId":"ce6e17f8b0","fileType":"ifc","fileName":"M-TGA-LK-32.ifc","fileSize":2611389,"userId":"efe9bf508e","streamId":"67e0d31bc7","branchName":"zero"}
    err: {
      "type": "Error",
      "message": "RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info.",
      "stack":
          Error: RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info.
              at doTask (/home/dim/source/speckle-server/packages/fileimport-service/src/daemon.js:179:32)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Timeout.tick [as _onTimeout] (/home/dim/source/speckle-server/packages/fileimport-service/src/daemon.js:284:5)
    }
```

What i'm getting terribly confused by is that this model opens fine in the ifc viewer itself, but throws this annoying error otherwise :/ 

Let us know if we can help debugging. 

### Version

tried latest from build.zip

### Relevant log output

```shell
ERROR: RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info. {"component":"fileimport-service","taskId":"ce6e17f8b0","fileId":"ce6e17f8b0","fileType":"ifc","fileName":"M-TGA-LK-32.ifc","fileSize":2611389,"userId":"efe9bf508e","streamId":"67e0d31bc7","branchName":"zero"}
    err: {
      "type": "Error",
      "message": "RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info.",
      "stack":
          Error: RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,774,GetSetArgument). Build with -s ASSERTIONS=1 for more info.
              at doTask (/home/dim/source/speckle-server/packages/fileimport-service/src/daemon.js:179:32)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Timeout.tick [as _onTimeout] (/home/dim/source/speckle-server/packages/fileimport-service/src/daemon.js:284:5)
    }
```

**Comment by beachtom** [comment]
Looks like the IFC model is invalid.

Admittedly, the error is not very clear - but I added some extra debugging now.

Line 130209 is used in a context it should not be - I think in IFCProject
