### ISSUE TITLE
[Bug]: Error when writing IfcFaceBound and IfcFaceOuterBound

### ISSUE THREAD

**Issue by clement-procal** [IFCjs/web-ifc#528]
### What happened?

A bug happened!

It looks like IfcFaceBound and IfcFaceOuterLoop has some issues when generating an IFC using web-ifc. 

With IFC2X3 Schema, it throws an exception:

```
BindingError: Cannot pass non-string to std::string
    at throwBindingError (web-ifc-api.js:5422:17)
    at Object.toWireType (web-ifc-api.js:6644:15)
    at __emval_as (web-ifc-api.js:6885:41)
    at web-ifc.wasm:0x6481c
    at web-ifc.wasm:0x6474a
    at web-ifc.wasm:0xaef46
    at web-ifc.wasm:0xae0b2
    at Object.WriteLine (eval at newFunc (web-ifc-api.js:6114:31), <anonymous>:11:10)
    at IfcAPI2.WriteRawLineData (web-ifc-api.js:64884:21)
    at IfcAPI2.WriteLine (web-ifc-api.js:64864:10)
```

With IFC4 and IFC4X3, it does not throws, but the output is incorrect:

```
...
#25=IFCPOLYLOOP((#21,#22,#23,#24));
#26=IFCFACEOUTERBOUND(#25,'[object Object]');
```

The expected output is :
```
...
#25=IFCPOLYLOOP((#21,#22,#23,#24));
#26=IFCFACEOUTERBOUND(#25,.T.);
```

Code example:
```
...
const loop1 = new WebIfc.IFC2X3.IfcPolyLoop([
  new WebIfc.IFC2X3.IfcCartesianPoint([
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0)]
  ),
  new WebIfc.IFC2X3.IfcCartesianPoint([
    new WebIfc.IFC2X3.IfcLengthMeasure(2), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0)]
  ),
  new WebIfc.IFC2X3.IfcCartesianPoint([
    new WebIfc.IFC2X3.IfcLengthMeasure(2), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(2)]
  ),
  new WebIfc.IFC2X3.IfcCartesianPoint([
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(0), 
    new WebIfc.IFC2X3.IfcLengthMeasure(2)]
  )
]);
const face1 = new WebIfc.IFC2X3.IfcFaceOuterBound(loop1, true);
this.ifcAPI.WriteLine(this.modelId, face1;
```

### Version

0.0.44

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by beachtom** [comment]
Are you reading in a model and then writing it - or are you generating model from scratch?

**Comment by clement-procal** [comment]
I am generating everything from scratch
