### ISSUE TITLE
[Bug]: RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/web-ifc#532]
### What happened?

Loading a file on https://platform.thatopen.com/app and i receive the error below.

### Version

latest

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Uncaught (in promise) RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at aG.getAllGeometriesIDs (9249.a39bde93b4db5cf6.js:6:393264)
    at async aG.export (9249.a39bde93b4db5cf6.js:6:392019)
```

### Anything else?

Model has been sent to antonio@thatopen.com

**Comment by vulevukusej** [comment]
@agviegas email sent. Thanks!

**Comment by agviegas** [comment]
File privately shared [here](https://drive.google.com/file/d/1fUfJ2eTPoqAkIsj-oB4PLQaoML1CrW14/view?usp=sharing).

**Comment by beachtom** [comment]
@agviegas  file does parse and generate successfully in web-ifc - so I think the bug is in components - so moving it
